// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpticaAPI.Data;

#nullable disable

namespace OpticaAPI.Migrations
{
    [DbContext(typeof(OpticaDbContext))]
    [Migration("20260814213843_AddMaterialToGraduacion")]
    partial class AddMaterialToGraduacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpticaAPI.Models.ExpedienteMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergias")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AntecedentesFamiliares")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EnfermedadesSistemicas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicamentosActuales")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("OpticaAPI.Models.Graduacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisenoLente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Diseno");

                    b.Property<decimal?>("DistanciaPupilar")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OptometristaId")
                        .HasColumnType("int");

                    b.Property<string>("OptometristaTexto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Optometrista");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int");

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Venta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("OptometristaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Graduaciones");
                });

            modelBuilder.Entity("OpticaAPI.Models.Optica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Opticas");
                });

            modelBuilder.Entity("OpticaAPI.Models.Optometrista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Optometristas");
                });

            modelBuilder.Entity("OpticaAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OpticaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("OpticaId");

                    b.HasIndex("Apellido", "Nombre");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("OpticaAPI.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OpticaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("OpticaId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("OpticaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OpticaId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("OpticaId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OpticaAPI.Models.ExpedienteMedico", b =>
                {
                    b.HasOne("OpticaAPI.Models.Paciente", "Paciente")
                        .WithOne()
                        .HasForeignKey("OpticaAPI.Models.ExpedienteMedico", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("OpticaAPI.Models.Graduacion", b =>
                {
                    b.HasOne("OpticaAPI.Models.Optometrista", "OptometristaNav")
                        .WithMany("Graduaciones")
                        .HasForeignKey("OptometristaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpticaAPI.Models.Paciente", "Paciente")
                        .WithMany("Graduaciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpticaAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Graduaciones")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("OpticaAPI.Models.Ojo", "OjoDerecho", b1 =>
                        {
                            b1.Property<int>("GraduacionId")
                                .HasColumnType("int");

                            b1.Property<string>("AV")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("OD_AV");

                            b1.Property<decimal?>("Adicion")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)")
                                .HasColumnName("OD_Adicion");

                            b1.Property<decimal?>("Cilindro")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OD_Cilindro");

                            b1.Property<int?>("Eje")
                                .HasColumnType("int")
                                .HasColumnName("OD_Eje");

                            b1.Property<decimal?>("Esfera")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OD_Esfera");

                            b1.HasKey("GraduacionId");

                            b1.ToTable("Graduaciones");

                            b1.WithOwner()
                                .HasForeignKey("GraduacionId");
                        });

                    b.OwnsOne("OpticaAPI.Models.Ojo", "OjoIzquierdo", b1 =>
                        {
                            b1.Property<int>("GraduacionId")
                                .HasColumnType("int");

                            b1.Property<string>("AV")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("OI_AV");

                            b1.Property<decimal?>("Adicion")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)")
                                .HasColumnName("OI_Adicion");

                            b1.Property<decimal?>("Cilindro")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OI_Cilindro");

                            b1.Property<int?>("Eje")
                                .HasColumnType("int")
                                .HasColumnName("OI_Eje");

                            b1.Property<decimal?>("Esfera")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OI_Esfera");

                            b1.HasKey("GraduacionId");

                            b1.ToTable("Graduaciones");

                            b1.WithOwner()
                                .HasForeignKey("GraduacionId");
                        });

                    b.Navigation("OjoDerecho")
                        .IsRequired();

                    b.Navigation("OjoIzquierdo")
                        .IsRequired();

                    b.Navigation("OptometristaNav");

                    b.Navigation("Paciente");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("OpticaAPI.Models.Optometrista", b =>
                {
                    b.HasOne("OpticaAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Optometristas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("OpticaAPI.Models.Paciente", b =>
                {
                    b.HasOne("OpticaAPI.Models.Optica", "Optica")
                        .WithMany("Pacientes")
                        .HasForeignKey("OpticaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Optica");
                });

            modelBuilder.Entity("OpticaAPI.Models.Sucursal", b =>
                {
                    b.HasOne("OpticaAPI.Models.Optica", "Optica")
                        .WithMany("Sucursales")
                        .HasForeignKey("OpticaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Optica");
                });

            modelBuilder.Entity("OpticaAPI.Models.Usuario", b =>
                {
                    b.HasOne("OpticaAPI.Models.Optica", "Optica")
                        .WithMany("Usuarios")
                        .HasForeignKey("OpticaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpticaAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Optica");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("OpticaAPI.Models.Optica", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Sucursales");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("OpticaAPI.Models.Optometrista", b =>
                {
                    b.Navigation("Graduaciones");
                });

            modelBuilder.Entity("OpticaAPI.Models.Paciente", b =>
                {
                    b.Navigation("Graduaciones");
                });

            modelBuilder.Entity("OpticaAPI.Models.Sucursal", b =>
                {
                    b.Navigation("Graduaciones");

                    b.Navigation("Optometristas");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
