// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpticaAPI.Data;

#nullable disable

namespace OpticaAPI.Migrations
{
    [DbContext(typeof(OpticaDbContext))]
    [Migration("20260406225358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpticaAPI.Models.Graduacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DistanciaPupilar")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Optometrista")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("PacienteId");

                    b.ToTable("Graduaciones");
                });

            modelBuilder.Entity("OpticaAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Apellido", "Nombre");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("OpticaAPI.Models.Graduacion", b =>
                {
                    b.HasOne("OpticaAPI.Models.Paciente", "Paciente")
                        .WithMany("Graduaciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpticaAPI.Models.Ojo", "OjoDerecho", b1 =>
                        {
                            b1.Property<int>("GraduacionId")
                                .HasColumnType("int");

                            b1.Property<string>("AV")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("OD_AV");

                            b1.Property<decimal?>("Adicion")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)")
                                .HasColumnName("OD_Adicion");

                            b1.Property<decimal?>("Cilindro")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OD_Cilindro");

                            b1.Property<int?>("Eje")
                                .HasColumnType("int")
                                .HasColumnName("OD_Eje");

                            b1.Property<decimal?>("Esfera")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OD_Esfera");

                            b1.HasKey("GraduacionId");

                            b1.ToTable("Graduaciones");

                            b1.WithOwner()
                                .HasForeignKey("GraduacionId");
                        });

                    b.OwnsOne("OpticaAPI.Models.Ojo", "OjoIzquierdo", b1 =>
                        {
                            b1.Property<int>("GraduacionId")
                                .HasColumnType("int");

                            b1.Property<string>("AV")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("OI_AV");

                            b1.Property<decimal?>("Adicion")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)")
                                .HasColumnName("OI_Adicion");

                            b1.Property<decimal?>("Cilindro")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OI_Cilindro");

                            b1.Property<int?>("Eje")
                                .HasColumnType("int")
                                .HasColumnName("OI_Eje");

                            b1.Property<decimal?>("Esfera")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("OI_Esfera");

                            b1.HasKey("GraduacionId");

                            b1.ToTable("Graduaciones");

                            b1.WithOwner()
                                .HasForeignKey("GraduacionId");
                        });

                    b.Navigation("OjoDerecho")
                        .IsRequired();

                    b.Navigation("OjoIzquierdo")
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("OpticaAPI.Models.Paciente", b =>
                {
                    b.Navigation("Graduaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
